version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - fullstack
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eduanalytics
    ports:
      - '5432:5432'
    volumes: 
     - postgres:/var/lib/postgresql/data
      # - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
    networks:
      - fullstack  

volumes:
  app:
  postgres:  

networks:
  fullstack:
    driver: bridge